// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/policy_client"
)

type Chunker struct {
	ChunkStub        func([]policy_client.PolicyV0) [][]policy_client.PolicyV0
	chunkMutex       sync.RWMutex
	chunkArgsForCall []struct {
		arg1 []policy_client.PolicyV0
	}
	chunkReturns struct {
		result1 [][]policy_client.PolicyV0
	}
	chunkReturnsOnCall map[int]struct {
		result1 [][]policy_client.PolicyV0
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Chunker) Chunk(arg1 []policy_client.PolicyV0) [][]policy_client.PolicyV0 {
	var arg1Copy []policy_client.PolicyV0
	if arg1 != nil {
		arg1Copy = make([]policy_client.PolicyV0, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.chunkMutex.Lock()
	ret, specificReturn := fake.chunkReturnsOnCall[len(fake.chunkArgsForCall)]
	fake.chunkArgsForCall = append(fake.chunkArgsForCall, struct {
		arg1 []policy_client.PolicyV0
	}{arg1Copy})
	stub := fake.ChunkStub
	fakeReturns := fake.chunkReturns
	fake.recordInvocation("Chunk", []interface{}{arg1Copy})
	fake.chunkMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Chunker) ChunkCallCount() int {
	fake.chunkMutex.RLock()
	defer fake.chunkMutex.RUnlock()
	return len(fake.chunkArgsForCall)
}

func (fake *Chunker) ChunkCalls(stub func([]policy_client.PolicyV0) [][]policy_client.PolicyV0) {
	fake.chunkMutex.Lock()
	defer fake.chunkMutex.Unlock()
	fake.ChunkStub = stub
}

func (fake *Chunker) ChunkArgsForCall(i int) []policy_client.PolicyV0 {
	fake.chunkMutex.RLock()
	defer fake.chunkMutex.RUnlock()
	argsForCall := fake.chunkArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Chunker) ChunkReturns(result1 [][]policy_client.PolicyV0) {
	fake.chunkMutex.Lock()
	defer fake.chunkMutex.Unlock()
	fake.ChunkStub = nil
	fake.chunkReturns = struct {
		result1 [][]policy_client.PolicyV0
	}{result1}
}

func (fake *Chunker) ChunkReturnsOnCall(i int, result1 [][]policy_client.PolicyV0) {
	fake.chunkMutex.Lock()
	defer fake.chunkMutex.Unlock()
	fake.ChunkStub = nil
	if fake.chunkReturnsOnCall == nil {
		fake.chunkReturnsOnCall = make(map[int]struct {
			result1 [][]policy_client.PolicyV0
		})
	}
	fake.chunkReturnsOnCall[i] = struct {
		result1 [][]policy_client.PolicyV0
	}{result1}
}

func (fake *Chunker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.chunkMutex.RLock()
	defer fake.chunkMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Chunker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ policy_client.Chunker = new(Chunker)
